Assignment: Introduction to Linear Algebra and NumPy
Objective:
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.

Working with NumPy
NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

Task 1:

Import the numpy library and check its version.

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.5.2


Creating a NumPy Array:
NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

Task 2:

Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5].
Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
Generate an array of 10 evenly spaced values between 0 and 5.

1. Create a 1D NumPy array

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)

[1 2 3 4 5]


2. Create a 2D NumPy array of shape (3, 3)

Using numbers from 1 to 9:

In [4]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3. Generate 10 evenly spaced values between 0 and 5

For evenly spaced values, use np.linspace():

In [5]:
arr3 = np.linspace(0, 5, 10)

print(arr3)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Indexing and Slicing Arrays:
Indexing and slicing allow you to access and modify specific elements of an array.

Task 3:

Access the element in the second row, third column of the 2D array you created above.
Slice the first two rows and the first two columns from the same array.
Modify the value in the last row and first column to 100.

In [7]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Access second row, third column
print(arr2[1, 2])

# Slice first two rows and first two columns
print(arr2[0:2, 0:2])

# Modify last row, first column
arr2[2, 0] = 100

print(arr2)

6
[[1 2]
 [4 5]]
[[  1   2   3]
 [  4   5   6]
 [100   8   9]]


Properties and Methods of NumPy Arrays
NumPy arrays have several useful properties and methods.

Task 4:

Find the shape, size, and data type of the 2D array.
Change the 1D array into a 2D array of shape (5,1).
Flatten a multi-dimensional array back into a 1D array.

In [9]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D array
arr2 = np.arange(1, 10).reshape(3, 3)

# Properties of 2D array
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data Type:", arr2.dtype)

# Convert 1D to 2D (5,1)
arr2d = arr1.reshape(5, 1)
print("\n2D Array:")
print(arr2d)

# Flatten 2D back to 1D
arr_flat = arr2.flatten()
print("\nFlattened Array:")
print(arr_flat)

Shape: (3, 3)
Size: 9
Data Type: int64

2D Array:
[[1]
 [2]
 [3]
 [4]
 [5]]

Flattened Array:
[1 2 3 4 5 6 7 8 9]


Operations on NumPy Arrays
Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

Task 5:

Add 5 to every element in the 1D array.
Multiply the 2D array by 3.
Perform matrix multiplication between the following two arrays:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [10]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("Add 5:", arr1 + 5)

# 2D array
arr2 = np.arange(1, 10).reshape(3, 3)
print("Multiply by 3:")
print(arr2 * 3)

# Matrix multiplication
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix Multiplication:")
print(A @ B)

Add 5: [ 6  7  8  9 10]
Multiply by 3:
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
Matrix Multiplication:
[[19 22]
 [43 50]]


Understanding Broadcasting
Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

Task 6:

Create a 3x3 matrix of ones and a 1D array of length 3.
Add the 1D array to each row of the matrix using broadcasting.

1. Create a 3×3 matrix of ones and a 1D array of length 3

In [12]:
matrix = np.ones((3, 3))
arr = np.array([1, 2, 3])

print(matrix)
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 2 3]


2. Add the 1D array to each row using broadcasting

In [13]:
result = matrix + arr

print(result)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
