Linear algebra is a branch of mathematics that deals with linear equations, matrices, vectors, and linear transformations. It provides a powerful set of tools for representing, analyzing, and manipulating data, and is widely used in various fields such as physics, engineering, computer science, and data science. Linear algebra involves the study of linear equations and their solutions, matrix operations such as addition, multiplication, and inversion, vector spaces and subspaces, linear transformations, eigenvectors and eigenvalues, and other related concepts.

Matrix operations: Matrices are used to represent datasets in data science, and matrix operations such as matrix multiplication, addition, and subtraction are used to perform operations on these datasets.

Linear transformations: Linear transformations are used to transform data into new coordinate systems or to represent data in a more concise and informative way.

Eigenvectors and eigenvalues: Eigenvectors and eigenvalues are used to analyze the structure of datasets and to identify important features.

Singular value decomposition (SVD): SVD is a powerful technique that is used to reduce the dimensionality of datasets and to identify important patterns in the data.

Optimization: Linear algebra is used in optimization problems such as linear programming, which is used to solve problems such as maximizing profits or minimizing costs subject to constraints.

Creating Numpy Array

In [2]:
import numpy as np

In [3]:
list1 = [1,2,3,4,5,6,7,8,9]
arry1 = np.array(list1)
arry1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arry1.shape

(9,)

In [5]:
arry1.ndim

1

In [6]:
list2 = [
    [1,2,3] , 
    [4,5,6] , 
    [7,8,9]
]
arry2 = np.array(list2)
arry2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arry2.shape

(3, 3)

In [8]:
arry2.ndim

2

In [9]:
list3 = [
    [
        [1,2,3] , 
        [4,5,6] , 
        [7,8,9]
    ],[
        [1,2,3] , 
        [4,5,6] , 
        [7,8,9]
    ]
]
arry3 = np.array(list3)
arry3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [10]:
arry3.shape

(2, 3, 3)

In [11]:
arry3.ndim

3

NumPy arrays can be created in several ways. Here are some of the most common methods:

array(): Creates NumPy arrays from Python lists
zeros(): Creates NumPy arrays with all elements initialized to 0
ones(): Creates NumPy arrays with all elements initialized to 1
full(): Creates an array with all elements initialized to same user-specified value
arange(): Creates NumPy arrays with a sequence of values (similar to python range() function)
linspace(): Creates NumPy arrays with a sequence of evenly spaced values
diag(): Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
eye(): Creates NumPy array with ones on the diagonal and zeros elsewhere
identity(): Creates an identity matrix
random.rand(): Creates NumPy array of random numbers sampled from a uniform distribution

In [12]:
np.zeros(shape = (2, 3,6), dtype= "int")

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [13]:
np.ones(shape = (3,6,6), dtype="int")

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [14]:
np.full(shape = (3,4), fill_value=6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [15]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [16]:
np.linspace((0, 1, 2), (30,20, 60) , num = 5, axis=0)

array([[ 0.  ,  1.  ,  2.  ],
       [ 7.5 ,  5.75, 16.5 ],
       [15.  , 10.5 , 31.  ],
       [22.5 , 15.25, 45.5 ],
       [30.  , 20.  , 60.  ]])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.random.randint(0, 50, size = (3, 2,4))

array([[[48, 13, 16, 35],
        [42,  1, 25,  9]],

       [[17, 41, 46, 21],
        [16, 32, 48,  3]],

       [[15, 13, 45, 11],
        [47, 14, 18, 24]]], dtype=int32)