NumPy Array Properties and Methods
NumPy arrays have several useful properties and methods that can be used to manipulate them.

shape: Property that returns the dimensions of the array
ndim: Property that returns number of array dimensions
dtype: Property that returns data-type of the array’s elements
T: Transpose of the array’s elements
reshape(): Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions
ravel(): Method that collapses all values into a single axis or dimension and returns view of original array
flatten(): Method that collapses all values into a single axis or dimension and returns an independent copy of original array
sum(): Method that returns the sum of all elements in an array
cumsum(): Method that returns cumulative sum over given axis
prod(): Method that compute product over given axis
max(): Method that returns the maximum along a given axis
argmax(): Method that returns indeces of the maximum values along a given axis
clip(): Clip values beyond range to threshold values
np.concatenate(): Method to concatenate two or more arrays
np.split(): Method to split an array into multiple sub-arrays
np.vstack(): Method to stack arrays vertically
np.hstack(): Method to stack arrays horizontally

In [1]:
import numpy as np

a = np.random.randint(10,50, size = (5, 2, 3), dtype="int16")
a.shape

(5, 2, 3)

In [2]:
a.ndim

3

In [3]:
a.dtype

dtype('int16')

In [4]:
a.T

array([[[20, 20, 20, 40, 30],
        [47, 40, 42, 17, 16]],

       [[36, 31, 18, 40, 11],
        [14, 27, 36, 16, 44]],

       [[23, 32, 46, 17, 47],
        [36, 39, 48, 47, 28]]], dtype=int16)

In [5]:
a.size

30

In [6]:
a = np.random.randint(10,50, size = (5, 4), dtype="int16")
a

array([[13, 10, 47, 43],
       [17, 12, 19, 26],
       [29, 30, 12, 46],
       [39, 42, 34, 16],
       [32, 28, 11, 37]], dtype=int16)

In [7]:
b = a.reshape(2,5,2)
b

array([[[13, 10],
        [47, 43],
        [17, 12],
        [19, 26],
        [29, 30]],

       [[12, 46],
        [39, 42],
        [34, 16],
        [32, 28],
        [11, 37]]], dtype=int16)

In [8]:
a.reshape(4,-1)

array([[13, 10, 47, 43, 17],
       [12, 19, 26, 29, 30],
       [12, 46, 39, 42, 34],
       [16, 32, 28, 11, 37]], dtype=int16)

In [9]:
a.flatten() #a.ravel()

array([13, 10, 47, 43, 17, 12, 19, 26, 29, 30, 12, 46, 39, 42, 34, 16, 32,
       28, 11, 37], dtype=int16)

In [10]:
a

array([[13, 10, 47, 43],
       [17, 12, 19, 26],
       [29, 30, 12, 46],
       [39, 42, 34, 16],
       [32, 28, 11, 37]], dtype=int16)

In [11]:
a.sum()

np.int64(543)

In [12]:
a.sum(axis = 0)

array([130, 122, 123, 168])

In [13]:
a.sum(axis = 1)

array([113,  74, 117, 131, 108])

In [14]:
a.trace() # diagonal sum

np.int64(53)

In [15]:
a.cumsum(axis = 1)

array([[ 13,  23,  70, 113],
       [ 17,  29,  48,  74],
       [ 29,  59,  71, 117],
       [ 39,  81, 115, 131],
       [ 32,  60,  71, 108]])

In [16]:
a.prod(dtype=float)

np.float64(4.1318098679439645e+27)

In [17]:
a.prod(axis = 0)

array([ 7998432,  4233600,  4007784, 30445376])

In [18]:
a.cumprod(axis = 1)

array([[    13,    130,   6110, 262730],
       [    17,    204,   3876, 100776],
       [    29,    870,  10440, 480240],
       [    39,   1638,  55692, 891072],
       [    32,    896,   9856, 364672]])

In [19]:
a

array([[13, 10, 47, 43],
       [17, 12, 19, 26],
       [29, 30, 12, 46],
       [39, 42, 34, 16],
       [32, 28, 11, 37]], dtype=int16)

In [20]:
a.argmax(axis = 0)

array([3, 3, 0, 2])

In [21]:
a.argmin(axis = 1)

array([1, 1, 2, 3, 2])

In [22]:
a.clip(min= 20, max = 40)

array([[20, 20, 40, 40],
       [20, 20, 20, 26],
       [29, 30, 20, 40],
       [39, 40, 34, 20],
       [32, 28, 20, 37]], dtype=int16)

In [23]:
# Concat or Joining
arr1 = np.random.randint(1,100, size = (3,3))
arr2 = np.random.randint(1,100, size = (3,3))
arr1, arr2

(array([[96, 42, 66],
        [ 4, 22, 42],
        [32, 32, 80]], dtype=int32),
 array([[60, 54, 46],
        [70, 41, 35],
        [47, 16, 92]], dtype=int32))

In [24]:
np.concatenate([arr1, arr2], axis = 0) #vstack

array([[96, 42, 66],
       [ 4, 22, 42],
       [32, 32, 80],
       [60, 54, 46],
       [70, 41, 35],
       [47, 16, 92]], dtype=int32)

In [25]:
np.concatenate([arr1, arr2], axis = 1) # hstack

array([[96, 42, 66, 60, 54, 46],
       [ 4, 22, 42, 70, 41, 35],
       [32, 32, 80, 47, 16, 92]], dtype=int32)

In [26]:

np.vstack((arr1, arr2))

array([[96, 42, 66],
       [ 4, 22, 42],
       [32, 32, 80],
       [60, 54, 46],
       [70, 41, 35],
       [47, 16, 92]], dtype=int32)

In [27]:
np.hstack([arr1, arr2])

array([[96, 42, 66, 60, 54, 46],
       [ 4, 22, 42, 70, 41, 35],
       [32, 32, 80, 47, 16, 92]], dtype=int32)