In [1]:
import numpy as np

1. Elementwise Operations
https://numpy.org/doc/2.5/reference/routines.math.html

In [2]:
a = np.array(
    [
        [4,6,8], 
        [1,2,4]
    ]
)
b = np.random.randint(1, 45, size = (2,3))
c = np.linspace((0,5), (60,100), num = 4, dtype=int)
a, b, c

(array([[4, 6, 8],
        [1, 2, 4]]),
 array([[26, 44, 29],
        [13, 43, 10]], dtype=int32),
 array([[  0,   5],
        [ 20,  36],
        [ 40,  68],
        [ 60, 100]]))

Arithmetic Operations

In [3]:
# a + b
np.add(a,b)

array([[30, 50, 37],
       [14, 45, 14]])

In [4]:
# a -b 
np.subtract(a, b)

array([[-22, -38, -21],
       [-12, -41,  -6]])

In [5]:
# a ** 2
np.pow(a, 2)

array([[16, 36, 64],
       [ 1,  4, 16]])

In [6]:
# a % b
quo, rem = np.divmod(b,a)
rem

array([[2, 2, 5],
       [0, 1, 2]])

Trignometric

In [7]:
np.sin(a)

array([[-0.7568025 , -0.2794155 ,  0.98935825],
       [ 0.84147098,  0.90929743, -0.7568025 ]])

In [8]:
cot = np.reciprocal(np.tan(b))
cot

array([[ 0.84835375, 56.48217935,  1.12721419],
       [ 2.15972864, -0.66738418,  1.54235105]])

Rounding operations

In [9]:
np.around(cot, 2)

array([[ 0.85, 56.48,  1.13],
       [ 2.16, -0.67,  1.54]])

In [10]:
np.floor(cot)

array([[ 0., 56.,  1.],
       [ 2., -1.,  1.]])

In [11]:
np.ceil(cot)

array([[ 1., 57.,  2.],
       [ 3., -0.,  2.]])

2. Matrix Operations

In [12]:
# Transpose

# b.T
bT = np.transpose(b)
bT

array([[26, 13],
       [44, 43],
       [29, 10]], dtype=int32)

In [13]:
# Matrix Multiplication

# a @ bT
# np.dot(a, bT)
res = a.dot(bT)
res

array([[600, 390],
       [230, 139]])

In [14]:
# Trace [Diagnoal sum]
d_sum = np.trace(res)
print(d_sum)

739


In [15]:
# Rank
np.linalg.matrix_rank(a)

np.int64(2)

In [16]:
# Determinat
b = np.random.randint(1, 5, size = (3,3))

det_b = np.linalg.det(b)
det_b

np.float64(-14.000000000000004)

In [17]:
# Inverse
inv_b = np.linalg.inv(b)
inv_b

array([[-7.40148683e-17, -5.00000000e-01,  5.00000000e-01],
       [-4.28571429e-01,  6.42857143e-01, -7.14285714e-02],
       [ 5.71428571e-01, -3.57142857e-01, -7.14285714e-02]])

Solve Equation : 4x + 2y = 8 , 5x + 3y = 9

In [18]:
A = np.array([[4,2] ,[5,3]])
B = np.array([8,9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([ 3., -2.])

In [19]:
# Array Broadcasting
A

array([[4, 2],
       [5, 3]])

In [20]:
B

array([8, 9])

In [21]:
A + B

array([[12, 11],
       [13, 12]])